// Code generated by goctl. DO NOT EDIT.
package types

type Resp struct {
	Code int    `json:"code"`
	Err  string `json:"err"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Active    bool   `json:"active"`
	Source    string `json:"source"`
	CreatedAt string `json:"createdAt"`
}

type GetUserResp struct {
	Data UserInfo `json:"data"`
	Resp
}

type GetUserReq struct {
	Id string `path:"userId"`
}

type CreateUserReq struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Source   string `json:"source"`
}

type CreateUserResp struct {
	Data string `json:"data"`
	Resp
}

type LoginReq struct {
	Identity string `json:"identity"`
	Password string `json:"password"`
}

type LoginClaims struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginResp struct {
	Data LoginClaims `json:"data"`
	Resp
}
